#!/usr/bin/env bash
set -euo pipefail

cd /var/tmp/remoteagent/workspaces/cc6mog23
DELAYED_INTRADAY_LIMIT=0 \
DELAYED_INTRADAY_OFFSET=0 \
DELAYED_INTRADAY_PARTITION_INDEX=1 \
DELAYED_INTRADAY_PARTITION_COUNT=5 \
DELAYED_INTRADAY_BATCH_SIZE=20 \
SQREAM_SERVICE=ingest \
DELAYED_INTRADAY_LOAD_ONLY=1 \
DELAYED_INTRADAY_PARTITION=b \
./run_delayed_intraday_cycle.sh
